# EN PRUEBAS - NO OFICIAL

version: '3.9'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
